[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "Kampfkarren/selene", version = "0.14" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.11" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "0.527" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
