name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: Install dependencies
      run: |
        luarocks install luafilesystem
        luarocks install luacov
        git clone https://github.com/alerque/luacov-coveralls.git --branch fix-actions-service-name
        luarocks install ./luacov-coveralls/rockspecs/luacov-coveralls-scm-0.rockspec
        luarocks install luacheck

    - name: Test
      run: |
        lua -lluacov bin/spec.lua
        luacheck src benchmarks examples

    - name: Report to Coveralls
      run: luacov-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}